$$$ exec p1 : [./pkathy.filler]
Plateau 24 40:
    0123456789012345678901234567890123456789
000 .............OO..OOOOOOOOOOOOOOOOOOOOOOO
001 .............ooOOOOOOOOOOOOOOOOOOOOOOOOO
002 ..............oOOOOOOOOOOOOOOOOOOOOOOOOO
003 ...O.O........OOOOOOOOOOOOOOOOOOOOOOOOOO
004 ...OOO.......OOOOOOOOOOOOOOOOOOOOOOOOOOO
005 .....OOOOOO.OOOOOOOOOOOOOOOOOOOOOOOOOOOO
006 ......OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
007 .........OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
008 .....OO.OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
009 ......OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
010 .....OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
011 .....OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
012 ...O.OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
013 ...OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
014 ...OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
015 ..OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
016 .OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
017 OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
018 OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.XOOOOOOO
019 OOOOOOOOOOOOOOOOOOOOOOOOOOOO.XXXXOOOOOOO
020 OOOOOOOOOOOOOOOOOOOOOOOOOOOOOXX.XOOOOOOO
021 OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
022 OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
023 ooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
Piece 20 2:
..
..
..
..
..
..
..
..
..
..
..
..
.*
**
.*
..
..
..
..
..
